### PR TITLE
Organize output of memory correction

### PR DESCRIPTION
**Pull request by thomas-muench**
This PR suggests the changes for the desired output of the data from the memory correction process.

### CODE REVIEW

**Comment by thomas-muench** [comment]
@twollnik The basic output works. However, I would need help with implementing the data frame for the memory coefficients. Specifically, how to add the memory coefficients as estimated from the individual standards to the existing data frame; see function `calculateMemoryCoefficients()`.

**Comment by thomas-muench** [comment]
@twollnik I guess you have seen that since your last commit the tests in `testProcessData` crash because of problems binding the two data frames of memory coefficients (mean and from all standards) with `bind_cols()`. The problem seems to be differing number of columns of 6 vs 12.

I then started to wonder why the mean mem. coefficients only run from 1 to 6. In the tested example data files we have the same standards being injected from two consecutive vials 6 times each (so, literally, in total 12 injections of the same standard). Can it be that upon calculating the mean, the mem. coefficients for the injections are averaged across all standards regardless if the same standard appears twice with injections from 1 to 6? In this case, the mean mem. coefficients are biased since the second injections 1-6 from the same standard are actually injections 7-12 in the measurement sequence, and we have a bug. (I hope it is somehow clear what I mean...if not, please excuse, it is late).

I had the same issue in my original implementation and resolved it by recalculating the injection number column so that for these "double standards" it runs monotonically from 1 to 12 (or whatever number it would be).

**Comment by twollnik** [comment]
I see your point, thank you for investigating this. I suggest modifying Lines 67 and 68 of `processData` to include one additional step:

```R
# replace lines 67 and 68 with this:
datasets <- datasets %>%
    groupStandardsInBlocks(config) %>%
    normalizeInjectionNumbers() %>%
    associateStandardsWithConfigInfo(config)
```
```R
# normalizeInjectionNumbers could look something like this
normalizeInjectionNumbers <- function(datasets){
    map(datasets, function(dataset){
         dataset %>% 
            group_by(`Identifier 1`, block) %>% 
            mutate(`Inj Nr` = row_number()) %>%
            ungroup() %>%
            arrange(Line)
    })
}
```

What do you think about this? If you like this approach, feel free to steal my code :wink:

**Comment by thomas-muench** [comment]
Thanks a lot for the code suggestion! I guess this will solve the problem. I will implement it and write tests to check the behaviour.

**Comment by thomas-muench** [comment]
Your suggested code works and I will merge and delete this branch now.

**Pull request merged**
